"""creacion_de_tablas

Revision ID: df203cc90e1b
Revises: 
Create Date: 2025-10-27 08:58:16.575647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df203cc90e1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('id_trabajador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion_trabajo', sa.String(length=255), nullable=False),
    sa.Column('correo_trabajador', sa.String(length=255), nullable=False),
    sa.Column('telefono_trabajador', sa.String(length=13), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('foto_trabajador', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_trabajador')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('telefono', sa.String(length=13), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('administradores',
    sa.Column('id_administrador', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo_admin', sa.String(length=255), nullable=False),
    sa.Column('nivel_acceso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_administrador')
    )
    op.create_table('direcciones',
    sa.Column('id_direccion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('direccion_completa', sa.String(length=255), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_direccion')
    )
    op.create_table('disponibilidad_trabajadores',
    sa.Column('id_disponibilidad', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'OCUPADO', 'INACTIVO', name='estado'), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajadores.id_trabajador'], ),
    sa.PrimaryKeyConstraint('id_disponibilidad')
    )
    op.create_table('notificaciones',
    sa.Column('id_notificacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_notificacion', sa.String(length=255), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajadores.id_trabajador'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('servicios',
    sa.Column('id_servicio', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_servicio', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('tarifa', sa.Integer(), nullable=False),
    sa.Column('tipo_tarifa', sa.String(length=100), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajadores.id_trabajador'], ),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_table('solicitudes_servicios',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=False),
    sa.Column('direccion_servicio', sa.String(length=255), nullable=False),
    sa.Column('descripcion_servicio', sa.String(length=255), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicios.id_servicio'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('mensajes',
    sa.Column('id_mensaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('id_solicitud', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_trabajador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_servicios.id_solicitud'], ),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajadores.id_trabajador'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_servicios.id_solicitud'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_table('resenas',
    sa.Column('id_resena', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentarios', sa.String(length=500), nullable=False),
    sa.Column('fecha_resena', sa.DateTime(), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_trabajador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes_servicios.id_solicitud'], ),
    sa.ForeignKeyConstraint(['id_trabajador'], ['trabajadores.id_trabajador'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resenas')
    op.drop_table('pagos')
    op.drop_table('mensajes')
    op.drop_table('solicitudes_servicios')
    op.drop_table('servicios')
    op.drop_table('notificaciones')
    op.drop_table('disponibilidad_trabajadores')
    op.drop_table('direcciones')
    op.drop_table('administradores')
    op.drop_table('usuarios')
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
